/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSendWhatsappRouteImport } from './routes/api/send-whatsapp'
import { Route as ApiPublicHooksCronCobrancasRouteImport } from './routes/api/public/hooks/cron-cobrancas'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendWhatsappRoute = ApiSendWhatsappRouteImport.update({
  id: '/api/send-whatsapp',
  path: '/api/send-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCronCobrancasRoute =
  ApiPublicHooksCronCobrancasRouteImport.update({
    id: '/api/public/hooks/cron-cobrancas',
    path: '/api/public/hooks/cron-cobrancas',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/usuarios': typeof UsuariosRoute
  '/api/send-whatsapp': typeof ApiSendWhatsappRoute
  '/api/public/hooks/cron-cobrancas': typeof ApiPublicHooksCronCobrancasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/usuarios': typeof UsuariosRoute
  '/api/send-whatsapp': typeof ApiSendWhatsappRoute
  '/api/public/hooks/cron-cobrancas': typeof ApiPublicHooksCronCobrancasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/usuarios': typeof UsuariosRoute
  '/api/send-whatsapp': typeof ApiSendWhatsappRoute
  '/api/public/hooks/cron-cobrancas': typeof ApiPublicHooksCronCobrancasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/configuracoes'
    | '/landing'
    | '/login'
    | '/usuarios'
    | '/api/send-whatsapp'
    | '/api/public/hooks/cron-cobrancas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/configuracoes'
    | '/landing'
    | '/login'
    | '/usuarios'
    | '/api/send-whatsapp'
    | '/api/public/hooks/cron-cobrancas'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/configuracoes'
    | '/landing'
    | '/login'
    | '/usuarios'
    | '/api/send-whatsapp'
    | '/api/public/hooks/cron-cobrancas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  UsuariosRoute: typeof UsuariosRoute
  ApiSendWhatsappRoute: typeof ApiSendWhatsappRoute
  ApiPublicHooksCronCobrancasRoute: typeof ApiPublicHooksCronCobrancasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-whatsapp': {
      id: '/api/send-whatsapp'
      path: '/api/send-whatsapp'
      fullPath: '/api/send-whatsapp'
      preLoaderRoute: typeof ApiSendWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cron-cobrancas': {
      id: '/api/public/hooks/cron-cobrancas'
      path: '/api/public/hooks/cron-cobrancas'
      fullPath: '/api/public/hooks/cron-cobrancas'
      preLoaderRoute: typeof ApiPublicHooksCronCobrancasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  UsuariosRoute: UsuariosRoute,
  ApiSendWhatsappRoute: ApiSendWhatsappRoute,
  ApiPublicHooksCronCobrancasRoute: ApiPublicHooksCronCobrancasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
